In [2]:
from visual_behavior import database as db


In [3]:
ophys_session_id = 845842114
ophys_experiment_ids = (
    db
    .lims_query('select * from ophys_experiments where ophys_session_id = {}'.format(ophys_session_id))['id']
    .values
)
ophys_experiment_ids

array([846546341, 846546326, 846546328, 846546335, 846546339, 846546337,
       846546331, 846546333])

In [4]:
from allensdk.brain_observatory.behavior.behavior_ophys_session import BehaviorOphysSession
experiment_id = 958527481 #846546339
session = BehaviorOphysSession.from_lims(experiment_id)
len(session.ophys_timestamps)

/home/dougo/Code/AllenSDK/allensdk/brain_observatory/behavior/behavior_ophys_api/behavior_ophys_nwb_api.py:9: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning: The loaded sync file contains the following deprecated line label keys: {'cam2_exposure', 'cam1_exposure'}. Consider updating the sync file line labels.
  self._check_line_labels()


48332

In [5]:
import visual_behavior.data_access.loading as loading
dataset = loading.get_ophys_dataset(experiment_id)
len(dataset.ophys_timestamps)

/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning:

The loaded sync file contains the following deprecated line label keys: {'cam2_exposure', 'cam1_exposure'}. Consider updating the sync file line labels.

/home/dougo/Code/AllenSDK/allensdk/brain_observatory/sync_dataset.py:109: UserWarning:

The loaded sync file contains the following deprecated line label keys: {'cam2_exposure', 'cam1_exposure'}. Consider updating the sync file line labels.

ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351


resampling mesoscope 2P frame times


48332

In [9]:
dataset.ophys_timestamps[:5]

ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351


resampling mesoscope 2P frame times


array([8.70512, 8.79832, 8.89152, 8.98473, 9.07793])

In [10]:
dataset.ophys_timestamps[1000:1005]

ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351


resampling mesoscope 2P frame times


array([101.92054, 102.01376, 102.10699, 102.20021, 102.29343])

In [11]:
dataset.ophys_timestamps[-5:]

ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351


resampling mesoscope 2P frame times


array([4514.32226, 4514.41549, 4514.50873, 4514.60196, 4514.6952 ])

In [8]:
np.mean(np.diff(dataset.ophys_timestamps))

ERROR:visual_behavior.ophys.sync.process_sync:Sync photodiode error needs to be fixed. Using assumed monitor delay: 0.0351


0.023307970330062537